### ISSUE TITLE
crash when player's head in inventory

### ISSUE THREAD

**Issue by SunnyMenkov** [edoren/SkinChanger#17] opened 2022-11-19 21:58 UTC
player with someone's head in inventory can't join on server and crashes immediately after joining.
[crash-2022-11-20_00.53.08-client.txt](https://github.com/edoren/SkinChanger/files/10048012/crash-2022-11-20_00.53.08-client.txt)

**Comment by edoren** [comment] 2024-07-08 14:25
Could not reproduce, if this is still happening on latest versions please fill this:

**Describe the bug**
A clear and concise description of what the bug is.

**Mod Loader**
 - [ ] Forge
 - [ ] NeoForge
 - [ ] Fabric

**Version Info (Please complete the following information)**
 - Mod Loader: [e.g. 51.0.22]
 - SkinChanger Version: [e.g. 0.6.1]
 - Minecraft Version: [e.g. 1.21.0]

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
Add logs to help explain your problem. You can find them inside the logs folder of your Minecraft instance.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Comment by edoren** [comment] 2024-07-08 14:25
Closed as not reproducible

**Closed by edoren** 2024-07-08 14:25 UTC
Labels: bug
