### ISSUE TITLE
/skin Not Showing Up

### ISSUE THREAD

**Issue by EdicalGH** [edoren/SkinChanger#46] opened 2024-10-18 01:27 UTC
**Describe the bug**
The best way to describe it is the command is just not existing. It's installed both client and server side and I do have OP

**Mod Loader**
 - [ X ] Forge

**Version Info**
 - Mod Loader: [47.3.11]
 - SkinChanger Version: [0.6.0]
 - Minecraft Version: [1.20.1]

**To Reproduce**
1. Open Chat
2. Type /skin
3. Lights up red like it doesnt exist

**Expected behavior**
Let me use the command.

**Screenshots**
![image](https://github.com/user-attachments/assets/e6707090-4137-4e32-9010-cfbb79160f20)

**Comment by edoren** [comment] 2024-10-22 21:13
Hello! Please provide some logs to identify the cause of the issue

**Comment by edoren** [comment] 2024-10-26 19:50
Migth be related to https://github.com/edoren/SkinChanger/issues/47. It should be fixed on latest 0.6.6 release. Closing this issue, if the error happen let me know

**Closed by edoren** 2024-10-26 19:50 UTC
